# Generated by Django 4.0.1 on 2023-11-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_alter_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
