# Generated by Django 4.0.1 on 2023-11-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_vendor_status_alter_vendor_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date_and_time',
            field=models.DateField(),
        ),
    ]
