# Generated by Django 4.0.1 on 2023-11-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_notification_date_and_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_request',
            name='date_and_time',
            field=models.DateField(),
        ),
    ]
