# Generated by Django 4.0.1 on 2023-11-14 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_product_request_date_and_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='PRODUCT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='VENDOR',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.vendor'),
            preserve_default=False,
        ),
    ]
