# Generated by Django 4.0.1 on 2023-11-25 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_product_request_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addinstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst', models.CharField(max_length=500)),
                ('photo', models.CharField(max_length=500)),
                ('date', models.DateField(max_length=100)),
                ('loginid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login')),
            ],
        ),
    ]
